// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy62Pk9RmZrBmG9h7XmOvMpAl_8Gm8C1A',
    appId: '1:580821837549:web:eb0eca980875112e4b4ee4',
    messagingSenderId: '580821837549',
    projectId: 'employeeapp-d928b',
    authDomain: 'employeeapp-d928b.firebaseapp.com',
    storageBucket: 'employeeapp-d928b.appspot.com',
    measurementId: 'G-65F8JCBKD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXVSAsPMcriXxOIRWChd2GQdoNR6XIyww',
    appId: '1:580821837549:android:cba3eb4725d6a1024b4ee4',
    messagingSenderId: '580821837549',
    projectId: 'employeeapp-d928b',
    storageBucket: 'employeeapp-d928b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXyv0cw53dFfFgFAx5hjX_5gnXw_2e5a4',
    appId: '1:580821837549:ios:0526544dda3f27b94b4ee4',
    messagingSenderId: '580821837549',
    projectId: 'employeeapp-d928b',
    storageBucket: 'employeeapp-d928b.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXyv0cw53dFfFgFAx5hjX_5gnXw_2e5a4',
    appId: '1:580821837549:ios:0526544dda3f27b94b4ee4',
    messagingSenderId: '580821837549',
    projectId: 'employeeapp-d928b',
    storageBucket: 'employeeapp-d928b.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy62Pk9RmZrBmG9h7XmOvMpAl_8Gm8C1A',
    appId: '1:580821837549:web:7ffab43efd54823c4b4ee4',
    messagingSenderId: '580821837549',
    projectId: 'employeeapp-d928b',
    authDomain: 'employeeapp-d928b.firebaseapp.com',
    storageBucket: 'employeeapp-d928b.appspot.com',
    measurementId: 'G-2YK4CYPQT6',
  );
}
